---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "${SERVICE_NAME}"
    namespace: "${NAMESPACE}"
  spec:
    type: LoadBalancer
    ports:
    - name: "http"
      port: ${INTERNAL_PORT}
    selector:
      app.kubernetes.io/name: "${SERVICE_NAME}"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app.kubernetes.io/runtime: "quarkus"
      app.kubernetes.io/name: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
    namespace: "${NAMESPACE}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          app.kubernetes.io/runtime: "quarkus"
          app.kubernetes.io/name: "${SERVICE_NAME}"
        namespace: "${NAMESPACE}"
      spec:
        containers:
        - image: "${CONTAINER_REGISTRY_URL}/${SERVICE_NAME}"
          name: "${SERVICE_NAME}"
          ports:
          - containerPort: ${INTERNAL_PORT}
            name: "http"
            protocol: "TCP"
      