version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Later versions of HTML Unit does not work properly when finding elements remotely.
      - dependency-name: net.sourceforge.htmlunit:htmlunit